version: "3.9"
services:
  keystone:
    build: ./keystone
    ports: 
      - 3000:3000
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: 
      POSTGRES_USER: postgres
      POSTGRES_DB: bedbug
  nextjs: 
    build: ./next

    ports:
      - 3001:3001
    


