version: "3.9"
services:

  monorepo:
    image: monorepo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: bedbug
      POSTGRES_PASSWORD: postgres
    


    




