FROM node:18-buster AS builder

# Set working directory
WORKDIR /usr/src/app
RUN yarn global add turbo
COPY . .

RUN cat .env.staging
RUN ls -la

# First install dependencies (as they change less often)
COPY .gitignore .gitignore
COPY . .
RUN yarn install --ignore-scripts

COPY turbo.json turbo.json


# Build packages
RUN yarn package

RUN yarn build:staging

EXPOSE 3000
EXPOSE 3001
CMD ["yarn", "start:staging"]
