steps:
  - name: gcr.io/cloud-builders/gcloud
    id: 'Write .env'
    entrypoint: 'bash'
    args: ['-c', 'touch .env.staging']

  - name: gcr.io/cloud-builders/gcloud
    id: 'Write .env 2'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo ADMIN_USER_EMAIL=$$ADMIN_USER_EMAIL >> .env.staging \
        && echo ADMIN_USER_PASSWORD=$$ADMIN_USER_PASSWORD >> .env.staging \
        && echo DATABASE_URL=$$DATABASE_URL >> .env.staging \
        && echo COOKIE_SECRET=$$COOKIE_SECRET >> .env.staging \
        && echo POSITIONSTACK_API_ACCESS_KEY=$$POSITIONSTACK_API_ACCESS_KEY >> .env.staging \
        && echo DEPLOYMENT_TARGET=staging >> .env.staging \
        && echo NODE_ENV=production >> .env.staging \
        && echo SEED_COUNT=1000 >> .env.staging \
        && echo NEXT_PUBLIC_GRAPHQL_ENDPOINT=changeme >> .env.staging \
        && echo NEXT_PUBLIC_STRICT_MODE=true >> .env.staging
    secretEnv:
      [
        'POSITIONSTACK_API_ACCESS_KEY',
        'ADMIN_USER_EMAIL',
        'ADMIN_USER_PASSWORD',
        'COOKIE_SECRET',
        'DATABASE_URL',
      ]
    waitFor: ['Write .env']

  - name: gcr.io/cloud-builders/gcloud
    id: 'Debug 1'
    entrypoint: 'bash'
    args: ['-c', 'ls -la']
    waitFor: ['Write .env 2']

  - name: gcr.io/cloud-builders/gcloud
    id: 'Debug 2'
    entrypoint: 'bash'
    args: ['-c', 'cat .env.staging']
    waitFor: ['Debug 1']

  # # Install Cloud SQL proxy
  # - id: proxy-install
  #   name: gcr.io/cloud-builders/yarn
  #   entrypoint: sh
  #   args:
  #     - '-c'
  #     - 'wget https://storage.googleapis.com/cloudsql-proxy/v1.20.1/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy && chmod +x cloud_sql_proxy'
  #   waitFor: ['-']

  # # Migrate database schema to the latest version
  # # https://knexjs.org/#Migrations-CLI
  # - id: start-proxy
  #   name: gcr.io/cloud-builders/gcloud
  #   entrypoint: sh
  #   args:
  #     - '-c'
  #     - './cloud_sql_proxy -dir=/workspace/cloudsql -instances=bedbug-365120:us-central1:bedbug'
  #   timeout: '1200s'
  #   waitFor: ['proxy-install']

  # - id: debug
  #   name: 'ubuntu'
  #   entrypoint: 'bash'
  #   args: ['-c', 'sleep 5 && pwd && ls -la cloudsql']
  #   waitFor: ['-']

  # Build from Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Container Image'
    args:
      - 'build'
      - '--file=./apps/keystone/Dockerfile.staging'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bedbug-staging-keystone:$COMMIT_SHA'
      - '.'
    waitFor: ['Debug 2']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Container Image To Registry'
    args: ['push', 'gcr.io/$PROJECT_ID/bedbug-staging-keystone:$COMMIT_SHA']
    waitFor: ['Build Container Image']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'bedbug-staging-keystone',
        '--image',
        'gcr.io/$PROJECT_ID/bedbug-staging-keystone:$COMMIT_SHA',
        '--region',
        'us-central1',
        '--service-account',
        'bedbug-staging-keystone@bedbug-365120.iam.gserviceaccount.com',
        '--add-cloudsql-instances',
        'bedbug-365120:us-central1:bedbug',
        '--update-env-vars',
        'INSTANCE_CONNECTION_NAME=bedbug-365120:us-central1:bedbug',
      ]
    waitFor: ['Push Container Image To Registry']
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/POSITIONSTACK_API_ACCESS_KEY/versions/latest
      env: 'POSITIONSTACK_API_ACCESS_KEY'
    - versionName: projects/$PROJECT_ID/secrets/STAGING_ADMIN_USER_EMAIL/versions/latest
      env: 'ADMIN_USER_EMAIL'
    - versionName: projects/$PROJECT_ID/secrets/STAGING_ADMIN_USER_PASSWORD/versions/latest
      env: 'ADMIN_USER_PASSWORD'
    - versionName: projects/$PROJECT_ID/secrets/STAGING_COOKIE_SECRET/versions/latest
      env: 'COOKIE_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/STAGING_DATABASE_URL/versions/latest
      env: 'DATABASE_URL'
images: ['gcr.io/bedbug-365120/bedbug-staging-keystone:$COMMIT_SHA']
options:
  logging: CLOUD_LOGGING_ONLY
