steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args:
      [
        '-c',
        "gcloud secrets versions access latest --secret=bedbug-staging-env --format='get(payload.data)' | tr '_-' '/+' | base64 -d > .env.staging",
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--file=./apps/keystone/Dockerfile.staging'
      - '.'
    id: 'bedbug-keystone-staging'
