steps:
  # Read Environment Variables from Secret Manager
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args:
      [
        '-c',
        "gcloud secrets versions access latest --secret=bedbug-staging-env --format='get(payload.data)' | tr '_-' '/+' | base64 -d > .env.staging",
      ]

  # Build from Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--file=./apps/keystone/Dockerfile.staging'
      - '-t'
      - 'bedbug-staging-keystone/$PROJECT_ID/image'
      - '.'
    id: 'bedbug-keystone-staging'

images: ['bedbug-staging-keystone/$PROJECT_ID/image']
