steps:
  # Read Environment Variables from Secret Manager
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args:
      [
        '-c',
        "gcloud secrets versions access latest --secret=bedbug-staging-env --format='get(payload.data)' | tr '_-' '/+' | base64 -d > .env.staging",
      ]

  # # Install Cloud SQL proxy
  # - id: proxy-install
  #   name: gcr.io/cloud-builders/yarn
  #   entrypoint: sh
  #   args:
  #     - '-c'
  #     - 'wget https://storage.googleapis.com/cloudsql-proxy/v1.20.1/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy && chmod +x cloud_sql_proxy'
  #   waitFor: ['-']

  # # Migrate database schema to the latest version
  # # https://knexjs.org/#Migrations-CLI
  # - id: start-proxy
  #   name: gcr.io/cloud-builders/gcloud
  #   entrypoint: sh
  #   args:
  #     - '-c'
  #     - './cloud_sql_proxy -dir=/workspace/cloudsql -instances=bedbug-365120:us-central1:bedbug'
  #   timeout: '1200s'
  #   waitFor: ['proxy-install']

  # - id: debug
  #   name: 'ubuntu'
  #   entrypoint: 'bash'
  #   args: ['-c', 'sleep 5 && pwd && ls -la cloudsql']
  #   waitFor: ['-']

  # Build from Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build container image'
    args:
      - 'build'
      - '--file=./apps/keystone/Dockerfile.staging'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bedbug-keystone:$COMMIT_SHA'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bedbug-keystone:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'bedbug-keystone',
        '--image',
        'gcr.io/bedbug-365120/bedbug-keystone:$COMMIT_SHA',
        '--region',
        'us-central1',
      ]

images: ['gcr.io/bedbug-365120/bedbug-keystone:$COMMIT_SHA']
